import type { Metadata } from "next";
import PageHeader from "@/components/PageHeader";
import "./globals.css";
import  {inter, dancingScript,roboto} from "../fonts"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="h-20 bg-background-light">
          <PageHeader />
        </div>

        {children}
      </body>
    </html>
  );
}
