import type { Metadata } from "next";
import PageHeader from "@/components/PageHeader";
import PageFooter from "@/components/PageFooter";
import "./globals.css";
import { inter, dancingScript, roboto } from "../fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} min-h-screen flex flex-col`}>
        <PageHeader />
        <main className="flex-1">{children}</main>{" "}
        {/* Flex-grow main content */}
        <PageFooter />
      </body>
    </html>
  );
}
